Vagrant.configure("2") do |config|

  # No need to add this if initiated like this: vagrant init ubuntu/focal64
  config.vm.box = "ubuntu/focal64"

  config.vm.define "web" do |web|
  web.vm.hostname = "web"
  web.vm.network "private_network", ip: "192.168.10.20"
  end

  config.vm.define "db" do |db|
  db.vm.hostname = "db"
  db.vm.network "private_network", ip: "192.168.10.30"
  end

  # Read the SSH public key from the file
  public_key_path = File.expand_path("id_rsa.pub", File.dirname(__FILE__))
  public_key = File.read(public_key_path).strip

  # Apply the provision script to all VMs
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    echo "" >> /home/vagrant/.ssh/authorized_keys
    echo "#{public_key}" >> /home/vagrant/.ssh/authorized_keys
  SHELL

end
